INSERT INTO musicsite.performers (id, average, first_name, last_name, proposition, pseudonym) VALUES (1, 3.5, 'Ryszard', 'Andrzejewski', false, 'Peja');
INSERT INTO musicsite.performers (id, average, first_name, last_name, proposition, pseudonym) VALUES (2, 0, 'Bob', 'Marley', false, 'Bob Marley & The Wailers');
INSERT INTO musicsite.performers (id, average, first_name, last_name, proposition, pseudonym) VALUES (3, 0, 'Earl', 'Simmons', false, 'DMX');
INSERT INTO musicsite.performers (id, average, first_name, last_name, proposition, pseudonym) VALUES (4, 0, null, null, false, 'A Tribe Called Quest');
INSERT INTO musicsite.performers (id, average, first_name, last_name, proposition, pseudonym) VALUES (5, 0, 'Piotr', 'Kowalczyk', false, 'Tau');
INSERT INTO musicsite.performers (id, average, first_name, last_name, proposition, pseudonym) VALUES (6, 0, 'Lauryn', 'Hill', false, 'Lauryn Hill');
INSERT INTO musicsite.performers (id, average, first_name, last_name, proposition, pseudonym) VALUES (7, 0, 'Adam', 'Zieliński', false, 'Łona');
INSERT INTO musicsite.performers (id, average, first_name, last_name, proposition, pseudonym) VALUES (8, 0, 'Riley Ben', 'King', true, 'B.B. King');
INSERT INTO musicsite.performers (id, average, first_name, last_name, proposition, pseudonym) VALUES (9, 0, 'Eric', 'Clapton', true, 'Eric Clapton');
INSERT INTO musicsite.performers (id, average, first_name, last_name, proposition, pseudonym) VALUES (10, 0, 'Erykah', 'Badu', true, 'Erykah Badu');
INSERT INTO musicsite.performers (id, average, first_name, last_name, proposition, pseudonym) VALUES (11, 0, '---', '---', true, 'Esbjorn Svensson Trio');
INSERT INTO musicsite.performers (id, average, first_name, last_name, proposition, pseudonym) VALUES (12, 0, 'Isaac', 'Hayes', true, 'Isaac Hayes');
INSERT INTO musicsite.performers (id, average, first_name, last_name, proposition, pseudonym) VALUES (13, 0, 'Jacek', 'Kaczmarski', true, 'Jacek Kaczmarski');
INSERT INTO musicsite.performers (id, average, first_name, last_name, proposition, pseudonym) VALUES (14, 0, 'Przemysław', 'Gintrowski', true, 'Przemysław Gintrowski');
INSERT INTO musicsite.performers (id, average, first_name, last_name, proposition, pseudonym) VALUES (15, 0, 'Zbigniew', 'Łapiński', true, 'Zbigniew Łapiński');
INSERT INTO musicsite.performers (id, average, first_name, last_name, proposition, pseudonym) VALUES (16, 0, '---', '---', true, 'Led Zeppelin');
INSERT INTO musicsite.performers (id, average, first_name, last_name, proposition, pseudonym) VALUES (17, 0, 'Miles', 'Davis', true, 'Miles Davis');
INSERT INTO musicsite.performers (id, average, first_name, last_name, proposition, pseudonym) VALUES (18, 0, 'Peter', 'Tosh', true, 'Peter Tosh');
INSERT INTO musicsite.performers (id, average, first_name, last_name, proposition, pseudonym) VALUES (19, 0, '---', '---', true, 'Pink Floyd');
INSERT INTO musicsite.performers (id, average, first_name, last_name, proposition, pseudonym) VALUES (20, 0, '---', '---', true, 'The Doors');
INSERT INTO musicsite.performers (id, average, first_name, last_name, proposition, pseudonym) VALUES (21, 0, '---', '---', true, 'The Rolling Stones');